# ============================================================
# POKÉMON: ECOS DE ANDARA — GENERADOR DE POKÉDEX EXPANDIDA PS1
# ============================================================

$DataDir = "c:\Users\Asus\Desktop\Proyecto\data"
$PokedexFile = Join-Path $DataDir "pokedex.json"

$pokedex = @{}
if (Test-Path $PokedexFile) {
    $existingRaw = Get-Content $PokedexFile -Raw | ConvertFrom-Json
    foreach ($prop in ($existingRaw | Get-Member -MemberType NoteProperty)) {
        $pokedex[$prop.Name] = $existingRaw.($prop.Name)
    }
}

# Lista expandida con especies para jefes, Alto Mando y Campeona
$newSpecies = @{
    "1" = @{ id = 1; name = "Bulbasaur"; types = @("grass", "poison"); stats = @{ hp = 45; attack = 49; defense = 49; special_attack = 65; special_defense = 65; speed = 45 }; evolution = @{ target_id = 2; target_name = "Ivysaur"; method = "level"; level = 16 }; learnset = @(@{ move = "tackle"; level = 1 }, @{ move = "vine_whip"; level = 3 }, @{ move = "energy_ball"; level = 20 }) }
    "2" = @{ id = 2; name = "Ivysaur"; types = @("grass", "poison"); stats = @{ hp = 60; attack = 62; defense = 63; special_attack = 80; special_defense = 80; speed = 60 }; evolution = @{ target_id = 3; target_name = "Venusaur"; method = "level"; level = 32 }; learnset = @(@{ move = "vine_whip"; level = 1 }, @{ move = "energy_ball"; level = 20 }) }
    "3" = @{ id = 3; name = "Venusaur"; types = @("grass", "poison"); stats = @{ hp = 80; attack = 82; defense = 83; special_attack = 100; special_defense = 100; speed = 80 }; mega_evolution = "venusaur"; learnset = @(@{ move = "giga_drain"; level = 1 }, @{ move = "sludge_bomb"; level = 1 }, @{ move = "energy_ball"; level = 1 }, @{ move = "earthquake"; level = 36 }) }
    "4" = @{ id = 4; name = "Charmander"; types = @("fire"); stats = @{ hp = 39; attack = 52; defense = 43; special_attack = 60; special_defense = 50; speed = 65 }; evolution = @{ target_id = 5; target_name = "Charmeleon"; method = "level"; level = 16 }; learnset = @(@{ move = "scratch"; level = 1 }, @{ move = "ember"; level = 4 }, @{ move = "flamethrower"; level = 24 }) }
    "5" = @{ id = 5; name = "Charmeleon"; types = @("fire"); stats = @{ hp = 58; attack = 64; defense = 58; special_attack = 80; special_defense = 65; speed = 80 }; evolution = @{ target_id = 6; target_name = "Charizard"; method = "level"; level = 36 }; learnset = @(@{ move = "ember"; level = 1 }, @{ move = "flamethrower"; level = 24 }) }
    "6" = @{ id = 6; name = "Charizard"; types = @("fire", "flying"); stats = @{ hp = 78; attack = 84; defense = 78; special_attack = 109; special_defense = 85; speed = 100 }; mega_evolution = "charizard_x"; learnset = @(@{ move = "flamethrower"; level = 1 }, @{ move = "dragon_claw"; level = 1 }, @{ move = "air_slash"; level = 1 }, @{ move = "fire_blast"; level = 36 }) }
    "7" = @{ id = 7; name = "Squirtle"; types = @("water"); stats = @{ hp = 44; attack = 48; defense = 65; special_attack = 50; special_defense = 64; speed = 43 }; evolution = @{ target_id = 8; target_name = "Wartortle"; method = "level"; level = 16 }; learnset = @(@{ move = "tackle"; level = 1 }, @{ move = "water_gun"; level = 3 }, @{ move = "surf"; level = 22 }) }
    "8" = @{ id = 8; name = "Wartortle"; types = @("water"); stats = @{ hp = 59; attack = 63; defense = 80; special_attack = 65; special_defense = 80; speed = 58 }; evolution = @{ target_id = 9; target_name = "Blastoise"; method = "level"; level = 36 }; learnset = @(@{ move = "water_gun"; level = 1 }, @{ move = "surf"; level = 22 }) }
    "9" = @{ id = 9; name = "Blastoise"; types = @("water"); stats = @{ hp = 79; attack = 83; defense = 100; special_attack = 85; special_defense = 105; speed = 78 }; mega_evolution = "blastoise"; learnset = @(@{ move = "hydro_pump"; level = 1 }, @{ move = "ice_beam"; level = 1 }, @{ move = "aura_sphere"; level = 1 }, @{ move = "flash_cannon"; level = 36 }) }
    "12" = @{ id = 12; name = "Butterfree"; types = @("bug", "flying"); stats = @{ hp = 60; attack = 45; defense = 50; special_attack = 90; special_defense = 80; speed = 70 }; learnset = @(@{ move = "bug_buzz"; level = 10 }, @{ move = "quiver_dance"; level = 25 }) }
    "18" = @{ id = 18; name = "Pidgeot"; types = @("normal", "flying"); stats = @{ hp = 83; attack = 80; defense = 75; special_attack = 70; special_defense = 70; speed = 101 }; mega_evolution = "pidgeot"; learnset = @(@{ move = "brave_bird"; level = 1 }, @{ move = "air_slash"; level = 1 }, @{ move = "roost"; level = 25 }) }
    "26" = @{ id = 26; name = "Raichu"; types = @("electric"); stats = @{ hp = 60; attack = 90; defense = 55; special_attack = 90; special_defense = 80; speed = 110 }; learnset = @(@{ move = "thunderbolt"; level = 1 }, @{ move = "volt_switch"; level = 1 }, @{ move = "extreme_speed"; level = 1 }) }
    "45" = @{ id = 45; name = "Vileplume"; types = @("grass", "poison"); stats = @{ hp = 75; attack = 80; defense = 85; special_attack = 110; special_defense = 90; speed = 50 }; learnset = @(@{ move = "giga_drain"; level = 1 }, @{ move = "sludge_bomb"; level = 1 }, @{ move = "moonblast"; level = 1 }) }
    "58" = @{ id = 58; name = "Growlithe"; types = @("fire"); stats = @{ hp = 55; attack = 70; defense = 45; special_attack = 70; special_defense = 50; speed = 60 }; evolution = @{ target_id = 59; target_name = "Arcanine"; method = "item"; item = "fire_stone" }; learnset = @(@{ move = "scratch"; level = 1 }, @{ move = "ember"; level = 4 }, @{ move = "flamethrower"; level = 20 }, @{ move = "crunch"; level = 28 }) }
    "59" = @{ id = 59; name = "Arcanine"; types = @("fire"); stats = @{ hp = 90; attack = 110; defense = 80; special_attack = 100; special_defense = 80; speed = 95 }; learnset = @(@{ move = "flamethrower"; level = 1 }, @{ move = "extreme_speed"; level = 1 }, @{ move = "crunch"; level = 1 }, @{ move = "close_combat"; level = 34 }) }
    "62" = @{ id = 62; name = "Poliwrath"; types = @("water", "fighting"); stats = @{ hp = 90; attack = 95; defense = 95; special_attack = 70; special_defense = 90; speed = 70 }; learnset = @(@{ move = "waterfall"; level = 1 }, @{ move = "close_combat"; level = 1 }, @{ move = "ice_punch"; level = 1 }) }
    "65" = @{ id = 65; name = "Alakazam"; types = @("psychic"); stats = @{ hp = 55; attack = 50; defense = 45; special_attack = 135; special_defense = 95; speed = 120 }; mega_evolution = "alakazam"; learnset = @(@{ move = "psychic"; level = 1 }, @{ move = "shadow_ball"; level = 1 }, @{ move = "dazzling_gleam"; level = 1 }, @{ move = "calm_mind"; level = 25 }) }
    "68" = @{ id = 68; name = "Machamp"; types = @("fighting"); stats = @{ hp = 90; attack = 130; defense = 80; special_attack = 65; special_defense = 85; speed = 55 }; learnset = @(@{ move = "close_combat"; level = 1 }, @{ move = "stone_edge"; level = 1 }, @{ move = "knock_off"; level = 1 }, @{ move = "bullet_punch"; level = 1 }) }
    "73" = @{ id = 73; name = "Tentacruel"; types = @("water", "poison"); stats = @{ hp = 80; attack = 70; defense = 65; special_attack = 80; special_defense = 120; speed = 100 }; learnset = @(@{ move = "scald"; level = 1 }, @{ move = "sludge_bomb"; level = 1 }, @{ move = "ice_beam"; level = 1 }) }
    "76" = @{ id = 76; name = "Golem"; types = @("rock", "ground"); stats = @{ hp = 80; attack = 120; defense = 130; special_attack = 55; special_defense = 65; speed = 45 }; learnset = @(@{ move = "stone_edge"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "stealth_rock"; level = 1 }) }
    "94" = @{ id = 94; name = "Gengar"; types = @("ghost", "poison"); stats = @{ hp = 60; attack = 65; defense = 60; special_attack = 130; special_defense = 75; speed = 110 }; mega_evolution = "gengar"; learnset = @(@{ move = "shadow_ball"; level = 1 }, @{ move = "sludge_bomb"; level = 1 }, @{ move = "dazzling_gleam"; level = 1 }, @{ move = "thunderbolt"; level = 1 }) }
    "130" = @{ id = 130; name = "Gyarados"; types = @("water", "flying"); stats = @{ hp = 95; attack = 125; defense = 79; special_attack = 60; special_defense = 100; speed = 81 }; mega_evolution = "gyarados"; learnset = @(@{ move = "waterfall"; level = 1 }, @{ move = "crunch"; level = 1 }, @{ move = "dragon_dance"; level = 1 }, @{ move = "earthquake"; level = 1 }) }
    "134" = @{ id = 134; name = "Vaporeon"; types = @("water"); stats = @{ hp = 130; attack = 65; defense = 60; special_attack = 110; special_defense = 95; speed = 65 }; learnset = @(@{ move = "scald"; level = 1 }, @{ move = "ice_beam"; level = 1 }, @{ move = "quick_attack"; level = 1 }) }
    "135" = @{ id = 135; name = "Jolteon"; types = @("electric"); stats = @{ hp = 65; attack = 65; defense = 60; special_attack = 110; special_defense = 95; speed = 130 }; learnset = @(@{ move = "thunderbolt"; level = 1 }, @{ move = "volt_switch"; level = 1 }, @{ move = "shadow_ball"; level = 1 }) }
    "136" = @{ id = 136; name = "Flareon"; types = @("fire"); stats = @{ hp = 65; attack = 130; defense = 60; special_attack = 95; special_defense = 110; speed = 65 }; learnset = @(@{ move = "flare_blitz"; level = 1 }, @{ move = "superpower"; level = 1 }, @{ move = "quick_attack"; level = 1 }) }
    "149" = @{ id = 149; name = "Dragonite"; types = @("dragon", "flying"); stats = @{ hp = 91; attack = 134; defense = 95; special_attack = 100; special_defense = 100; speed = 80 }; learnset = @(@{ move = "outrage"; level = 1 }, @{ move = "dragon_dance"; level = 1 }, @{ move = "extreme_speed"; level = 1 }, @{ move = "earthquake"; level = 1 }) }
    "181" = @{ id = 181; name = "Ampharos"; types = @("electric"); stats = @{ hp = 90; attack = 75; defense = 85; special_attack = 115; special_defense = 90; speed = 55 }; mega_evolution = "ampharos"; learnset = @(@{ move = "thunderbolt"; level = 1 }, @{ move = "dragon_pulse"; level = 1 }, @{ move = "focus_blast"; level = 1 }, @{ move = "volt_switch"; level = 1 }) }
    "196" = @{ id = 196; name = "Espeon"; types = @("psychic"); stats = @{ hp = 65; attack = 65; defense = 60; special_attack = 130; special_defense = 95; speed = 110 }; learnset = @(@{ move = "psychic"; level = 1 }, @{ move = "shadow_ball"; level = 1 }, @{ move = "calm_mind"; level = 1 }) }
    "197" = @{ id = 197; name = "Umbreon"; types = @("dark"); stats = @{ hp = 95; attack = 65; defense = 110; special_attack = 60; special_defense = 130; speed = 65 }; learnset = @(@{ move = "foul_play"; level = 1 }, @{ move = "toxic"; level = 1 }, @{ move = "protect"; level = 1 }) }
    "208" = @{ id = 208; name = "Steelix"; types = @("steel", "ground"); stats = @{ hp = 75; attack = 85; defense = 200; special_attack = 55; special_defense = 65; speed = 30 }; mega_evolution = "steelix"; learnset = @(@{ move = "iron_head"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "stealth_rock"; level = 1 }) }
    "212" = @{ id = 212; name = "Scizor"; types = @("bug", "steel"); stats = @{ hp = 70; attack = 130; defense = 100; special_attack = 55; special_defense = 80; speed = 65 }; mega_evolution = "scizor"; learnset = @(@{ move = "bullet_punch"; level = 1 }, @{ move = "u_turn"; level = 1 }, @{ move = "swords_dance"; level = 1 }, @{ move = "knock_off"; level = 1 }) }
    "248" = @{ id = 248; name = "Tyranitar"; types = @("rock", "dark"); stats = @{ hp = 100; attack = 134; defense = 110; special_attack = 95; special_defense = 100; speed = 61 }; mega_evolution = "tyranitar"; learnset = @(@{ move = "stone_edge"; level = 1 }, @{ move = "crunch"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "dragon_dance"; level = 1 }) }
    "254" = @{ id = 254; name = "Sceptile"; types = @("grass"); stats = @{ hp = 70; attack = 85; defense = 65; special_attack = 105; special_defense = 85; speed = 120 }; mega_evolution = "sceptile"; learnset = @(@{ move = "leaf_blade"; level = 1 }, @{ move = "dragon_pulse"; level = 1 }, @{ move = "energy_ball"; level = 1 }) }
    "257" = @{ id = 257; name = "Blaziken"; types = @("fire", "fighting"); stats = @{ hp = 80; attack = 120; defense = 70; special_attack = 110; special_defense = 70; speed = 80 }; mega_evolution = "blaziken"; learnset = @(@{ move = "flare_blitz"; level = 1 }, @{ move = "close_combat"; level = 1 }, @{ move = "swords_dance"; level = 1 }) }
    "260" = @{ id = 260; name = "Swampert"; types = @("water", "ground"); stats = @{ hp = 100; attack = 110; defense = 90; special_attack = 85; special_defense = 90; speed = 60 }; mega_evolution = "swampert"; learnset = @(@{ move = "waterfall"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "ice_punch"; level = 1 }) }
    "282" = @{ id = 282; name = "Gardevoir"; types = @("psychic", "fairy"); stats = @{ hp = 68; attack = 65; defense = 65; special_attack = 125; special_defense = 115; speed = 80 }; mega_evolution = "gardevoir"; learnset = @(@{ move = "moonblast"; level = 1 }, @{ move = "psychic"; level = 1 }, @{ move = "shadow_ball"; level = 1 }, @{ move = "calm_mind"; level = 1 }) }
    "302" = @{ id = 302; name = "Sableye"; types = @("dark", "ghost"); stats = @{ hp = 50; attack = 75; defense = 75; special_attack = 65; special_defense = 65; speed = 50 }; mega_evolution = "sableye"; learnset = @(@{ move = "knock_off"; level = 1 }, @{ move = "will_o_wisp"; level = 1 }, @{ move = "recover"; level = 1 }) }
    "350" = @{ id = 350; name = "Milotic"; types = @("water"); stats = @{ hp = 95; attack = 60; defense = 79; special_attack = 100; special_defense = 125; speed = 81 }; learnset = @(@{ move = "scald"; level = 1 }, @{ move = "ice_beam"; level = 1 }, @{ move = "recover"; level = 1 }, @{ move = "toxic"; level = 1 }) }
    "373" = @{ id = 373; name = "Salamence"; types = @("dragon", "flying"); stats = @{ hp = 95; attack = 135; defense = 80; special_attack = 110; special_defense = 80; speed = 100 }; mega_evolution = "salamence"; learnset = @(@{ move = "double_edge"; level = 1 }, @{ move = "dragon_dance"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "roost"; level = 1 }) }
    "376" = @{ id = 376; name = "Metagross"; types = @("steel", "psychic"); stats = @{ hp = 80; attack = 135; defense = 130; special_attack = 95; special_defense = 90; speed = 70 }; mega_evolution = "metagross"; learnset = @(@{ move = "meteor_mash"; level = 1 }, @{ move = "zen_headbutt"; level = 1 }, @{ move = "earthquake"; level = 1 }, @{ move = "bullet_punch"; level = 1 }) }
    "443" = @{ id = 443; name = "Gible"; types = @("dragon", "ground"); stats = @{ hp = 58; attack = 70; defense = 45; special_attack = 40; special_defense = 45; speed = 42 }; learnset = @(@{ move = "tackle"; level = 1 }, @{ move = "dragon_breath"; level = 5 }, @{ move = "earthquake"; level = 28 }) }
    "445" = @{ id = 445; name = "Garchomp"; types = @("dragon", "ground"); stats = @{ hp = 108; attack = 130; defense = 95; special_attack = 80; special_defense = 85; speed = 102 }; mega_evolution = "garchomp"; learnset = @(@{ move = "earthquake"; level = 1 }, @{ move = "dragon_claw"; level = 1 }, @{ move = "swords_dance"; level = 1 }, @{ move = "stone_edge"; level = 1 }) }
    "448" = @{ id = 448; name = "Lucario"; types = @("fighting", "steel"); stats = @{ hp = 70; attack = 110; defense = 70; special_attack = 115; special_defense = 70; speed = 90 }; mega_evolution = "lucario"; learnset = @(@{ move = "close_combat"; level = 1 }, @{ move = "aura_sphere"; level = 1 }, @{ move = "flash_cannon"; level = 1 }, @{ move = "extreme_speed"; level = 1 }) }
    "462" = @{ id = 462; name = "Magnezone"; types = @("electric", "steel"); stats = @{ hp = 70; attack = 70; defense = 115; special_attack = 130; special_defense = 90; speed = 60 }; learnset = @(@{ move = "thunderbolt"; level = 1 }, @{ move = "flash_cannon"; level = 1 }, @{ move = "volt_switch"; level = 1 }) }
    "471" = @{ id = 471; name = "Glaceon"; types = @("ice"); stats = @{ hp = 65; attack = 60; defense = 110; special_attack = 130; special_defense = 95; speed = 65 }; learnset = @(@{ move = "ice_beam"; level = 1 }, @{ move = "blizzard"; level = 1 }, @{ move = "shadow_ball"; level = 1 }) }
    "609" = @{ id = 609; name = "Chandelure"; types = @("ghost", "fire"); stats = @{ hp = 60; attack = 55; defense = 90; special_attack = 145; special_defense = 90; speed = 80 }; learnset = @(@{ move = "shadow_ball"; level = 1 }, @{ move = "flamethrower"; level = 1 }, @{ move = "energy_ball"; level = 1 }, @{ move = "will_o_wisp"; level = 1 }) }
    "637" = @{ id = 637; name = "Volcarona"; types = @("bug", "fire"); stats = @{ hp = 85; attack = 60; defense = 65; special_attack = 135; special_defense = 105; speed = 100 }; learnset = @(@{ move = "quiver_dance"; level = 1 }, @{ move = "flamethrower"; level = 1 }, @{ move = "bug_buzz"; level = 1 }, @{ move = "giga_drain"; level = 1 }) }
    "823" = @{ id = 823; name = "Corviknight"; types = @("flying", "steel"); stats = @{ hp = 98; attack = 87; defense = 105; special_attack = 53; special_defense = 85; speed = 67 }; learnset = @(@{ move = "brave_bird"; level = 1 }, @{ move = "iron_head"; level = 1 }, @{ move = "roost"; level = 1 }, @{ move = "u_turn"; level = 1 }) }
    "887" = @{ id = 887; name = "Dragapult"; types = @("dragon", "ghost"); stats = @{ hp = 88; attack = 120; defense = 75; special_attack = 100; special_defense = 75; speed = 142 }; learnset = @(@{ move = "dragon_claw"; level = 1 }, @{ move = "shadow_ball"; level = 1 }, @{ move = "u_turn"; level = 1 }, @{ move = "flamethrower"; level = 1 }) }
}

foreach ($k in $newSpecies.Keys) {
    $pokedex[$k] = $newSpecies[$k]
}

$pokedex | ConvertTo-Json -Depth 6 | Set-Content $PokedexFile -Encoding UTF8
Write-Host "Pokedex regional expandida con exito en $PokedexFile. Especies registradas: $($pokedex.Count)"
